### PR TITLE
malavika made changes

### PR DESCRIPTION
**Pull request by malavikaanand15**
Heyy!! Check if this is okay.

### CODE REVIEW

**Comment by vismaya74** [comment]
Hi malavika,
No this is not acceptable. please use your brain and work.

**Review by vismaya74 — CHANGES_REQUESTED** [review]
Hi malavika,
please add addition function

**Comment by malavikaanand15** [comment]
Hey Vismaya!! I have added the function.

**Review by vismaya74 — APPROVED** [review]
Hey malavika, 
thanks for your contribution

**Pull request merged**
